from __future__ import annotations

import json
from pathlib import Path

from .profiles import NPU_OFFLOAD_CHOICES


NPU_OFFLOAD_POLICY_CHOICES = ("recommended", "balanced", "fastest", "lowest-gpu")


def _load_json_object(path: str | Path) -> dict:
    with Path(path).expanduser().open("r", encoding="utf-8-sig") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"expected JSON object: {path}")
    return payload


def _normalize_policy(policy: str | None) -> str:
    normalized = str(policy or "balanced").strip().lower().replace("_", "-")
    if normalized not in NPU_OFFLOAD_POLICY_CHOICES:
        raise ValueError(f"npu offload policy must be one of {', '.join(NPU_OFFLOAD_POLICY_CHOICES)}")
    return normalized


def _candidate_from_policy(recommendation: dict, policy: str) -> dict | None:
    if policy == "fastest":
        candidate = recommendation.get("fastest")
    elif policy == "lowest-gpu":
        candidate = recommendation.get("lowest_gpu_utilization")
    elif policy == "balanced":
        candidate = recommendation.get("balanced")
    else:
        candidate = None
    return candidate if isinstance(candidate, dict) else None


def load_npu_offload_profile(summary_path: str | Path, *, policy: str | None = "balanced") -> dict:
    """Load a deployable NPU offload profile from a benchmark summary.

    The input is the `benchmark-summary.json` generated by
    `scripts/windows_gpu_npu_benchmark.ps1` or
    `scripts/benchmark_windows_gpu_npu_release.py`.
    """

    summary = _load_json_object(summary_path)
    recommendation = summary.get("recommendation") or {}
    if not isinstance(recommendation, dict):
        recommendation = {}
    normalized_policy = _normalize_policy(policy)
    candidate = _candidate_from_policy(recommendation, normalized_policy)
    if candidate is None:
        recommended = {
            "scenario": recommendation.get("recommended_scenario"),
            "npu_offload": recommendation.get("recommended_npu_offload"),
        }
        candidate = recommended if recommended.get("npu_offload") else None
    if candidate is None:
        candidate = {"scenario": "gpu_only", "npu_offload": "off"}

    npu_offload = str(candidate.get("npu_offload") or "off").strip().lower().replace("_", "-")
    if npu_offload == "gpu-only":
        npu_offload = "off"
    if npu_offload not in NPU_OFFLOAD_CHOICES:
        raise ValueError(f"benchmark recommendation contains unsupported npu_offload={npu_offload!r}")
    if npu_offload == "auto":
        npu_offload = "decoder"
    return {
        "summary_path": str(Path(summary_path).expanduser()),
        "policy": normalized_policy,
        "scenario": candidate.get("scenario") or recommendation.get("recommended_scenario") or "gpu_only",
        "npu_offload": npu_offload,
        "median_computed_rtf": candidate.get("median_computed_rtf"),
        "computed_rtf_speedup": candidate.get("computed_rtf_speedup"),
        "gpu_utilization_reduction": candidate.get("gpu_utilization_reduction"),
        "source_status": summary.get("status"),
    }
